### ISSUE TITLE
current_membership liquid extension?

### ISSUE THREAD

**Issue by peachananr** [locomotivecms/steam#108]
I may be missing something here but is there a way to get the currently backoffice logged in account on the site front end with liquid? I tried current_user but it returned {}.

Maybe something like this: https://github.com/locomotivecms/engine/pull/312 on Steam?

**Comment by did** [comment]
We could implement it but I don't see the use case for now. Another thing is related to the way Steam and Engine live together. For most installations, Steam serves pages within the Engine but sometimes you can setup standalone Steams which makes harder to get the current signed in user.
