### ISSUE TITLE
Integer issue in Duktape via Actions API

### ISSUE THREAD

**Issue by boie0025** [locomotivecms/steam#120]
On making a request to a JSON API that returns dates as INTs (since Epoch in MS), Duktape errors out, unable to parse the containing JSON.

Error:
`INTEGER 1536598528930 TOO BIG TO CONVERT TO 'INT'`

This was found specifically on OS X 10.13.6, Ruby 2.5.1p57, Steam 1.4.0, Wagon 2.4.0, Duktape 1.6.1.0

**Comment by did** [comment]
hi @boie0025, could you write a spec which would raise the error?

**Comment by did** [comment]
I'm also wondering if the new version of the duktape gem would solve that error.

**Comment by boie0025** [comment]
I'll get a PR with a spec here soon.  I did try upgrading, but rolled it back as it broke a bunch of specs.

**Comment by did** [comment]
Alright, I fixed it in the Duktape ruby gem (https://github.com/judofyr/duktape.rb/pull/43). I'm waiting for the author to accept it.
In the meantime, I think we can use my fork (all the tests in Steam pass).
