### ISSUE TITLE
with_scope on site.pages drops slug finder 

### ISSUE THREAD

**Issue by boie0025** [locomotivecms/steam#123]
Finding a page via {% with_scope %} does not honor the `slug` finder, instead overrides with `"slug.en"=>{"$ne"=>"404"}`

Example query:
```liquid
{% with_scope listed.ne: false, published.ne: false, is_layout.ne: true, slug: 'index' %}
```

This works locally with Wagon, but on Engine, looking through the logs, it's clear that the slug finder is dropped.  However, I was able to find a workaround:

``` liquid
{% with_scope listed.ne: false, published.ne: false, is_layout.ne: true, slug: { '$eq' => 'index'} %}
```

which is properly interpreted into a Mongo query as: `"slug.en"=>{"$eq"=>"index", "$ne"=>"404"}`

I suspect what's happening is when the `"$ne" => "404"` is added, it overrides whatever's there. (perhaps something with how this is added: https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/drops/site.rb#L30 )

**Comment by did** [comment]
Couldn't reproduce the bug. Here is the code I used to test within both Wagon and Engine:
```
{% with_scope listed.ne: true, published.ne: false, is_layout.ne: true, slug: 'index' %}

  {% assign page = site.pages.first %}

  {% if page %}
    <h2>{{ page.title }}</h2>
  {% else %}
    <p><i>Not found</i></p>
  {% endif %}

{% endwith_scope %}
```
