### ISSUE TITLE
Testing for presence of a value in url_picker

### ISSUE THREAD

**Issue by dotsi** [locomotivecms/steam#155]
Based on the resolution of #149 
the same syntax should work for url_picker. 

````
{% if section.settings.my_link is present %}
  <a href="{{ section.settings.my_link }}" />Link</a>
{% else %}
  <p>No link</p>
{% endif %}
````

This expression always evaluates to true even if you delete the url in the cms or never assign it.

**Comment by did** [comment]
this syntax should work now with the url picker. thanks!

**Comment by dotsi** [comment]
Thanks for the super quick fix!
