### ISSUE TITLE
Option to use sections without extra wrapping element

### ISSUE THREAD

**Issue by dotsi** [locomotivecms/steam#156]
Sections are the only part of Locomotivecms that outputs code that is not provided and controlled by the developer. 
Sections should be coded like blocks and use `{{ section.locomotive_attributes }}` in the wrapping element. 
For backwards compatibility the presence of `{{ section.locomotive_attributes }}` in the section template can be used to determine if a wrapper needs to be added or not. This could also help avoid issues when developers forget to add it.

**Comment by did** [comment]
- [] implement `{{ section.locomotive_attributes }}` in Steam
- [] update the editor in Engine (we rely on data attributes now to find a section)
- [] update Wagon generators (no need of the `class` section option)
- [] update the v4 documentation
