### ISSUE TITLE
editable_text editable in the back-office, but not used for rendering

### ISSUE THREAD

**Issue by proxygear** [locomotivecms/steam#165]
I got a layout, let's say `index.liquid`
within it :
```
{% block 'main' %}
{% endblock %}
{% include 'footer' %}
```
And the `footer.liquid`
```
{% editable_text 'value', fixed: true %}
Something
{% endeditable_text %}
```
The `value` was editable in the backoffice, but `Something` was never changed on the rendering.

I fixed it by surrounding the content of `footer.liquid` with a `block`.
I add a documentation modification request there for warning about this :
https://doc.locomotivecms.com/docs/tags

It would be nice to had a warning in wagon when a `editable_*` isn't within a block ?

**Comment by did** [comment]
hi @proxygear, editable_elements are not reliable when used in snippets. We recommend to not use them since we've got now sections.

**Comment by did** [comment]
...in other words, editable_elements are deprecated and will be removed at some point.
