### ISSUE TITLE
"Unable to compress and minify" when deploying ES6 syntax js thru steam

### ISSUE THREAD

**Issue by dahogenelst** [locomotivecms/steam#172]
I saw this warning being thrown by Wagon. 
```
  persisting javascripts/bundle.jsWarning: Unable to compress and minify it, error: Unexpected token: name (continues). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
 [done]
```
Possibly having to do something with [this issue](https://github.com/lautis/uglifier/issues/127). If I follow their suggestion, my ES6 JS is properly compressed and minified again.

I've replaced https://github.com/locomotivecms/steam/blob/67a5c77635226c6c8ccf86fda60402b9680fc91f/lib/locomotive/steam/initializers/sprockets.rb#L46 with `self.js_compressor  = Uglifier.new(harmony: true)`

I don't really know for certain if I am properly using ES6, mixing it up with old school JS or doing something else wrong, but this helped solve my issue!

If you want a PR for this, I can make one.

**Comment by did** [comment]
hey @dahogenelst! In my recent LocomotiveCMS websites, I don't use Sprockets anymore to manage my JS/CSS but rather Webpack. More information about it here: https://doc.locomotivecms.com/docs/manage-js-and-css-with-webpack.
