### ISSUE TITLE
XSS issue for Sanitize gem

### ISSUE THREAD

**Issue by dahogenelst** [locomotivecms/steam#188]
Hey Did,

I was trying to install the wagon gem on my Gentoo box and along the way I stumbled upon a security issue I'd like to inform you about. [Sanitize's history](https://github.com/rgrove/sanitize/blob/master/HISTORY.md) says versions 3.0.0 through 5.2.0 are effected.

I noticed a Pull request already bumping the version for this gem, but not far enough.

Just so you know! Let me know if you need a PR

**Comment by did** [comment]
thanks @dahogenelst. Fixed by https://github.com/locomotivecms/steam/commit/2ba725a09a4fe39c0d1a3bf3f18f728e78a43904
