### ISSUE TITLE
URI::BadURIError: both URI are relative

### ISSUE THREAD

**Issue by KazW** [locomotivecms/steam#40]
I'm trying to setup a new Locomotive instance on Heroku, I've managed to get it up and running and create a site, so far that's all working. Pushing sites to the engine works, however visiting them causes an error. This happens whenever I put a ```javascript_tag``` or ```stylesheet_tag``` in my template.

I've tracked the error to this line: https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/services/asset_host_service.rb#L21

I'd like to know how/where the attr_accessor for host is set so I can see why this is happening. I'm using S3 with a custom asset host, that has the protocol, so I don't think the carrierwave asset_host is being used here.

**Comment by did** [comment]
@KazW I've the feeling that it does not work because ````CarrierWave::Uploader::Base.asset_host```` (https://github.com/locomotivecms/engine/blob/master/lib/locomotive/steam_adaptor.rb#L10) doesn't include the protocol. 
https://github.com/locomotivecms/heroku-instant-deploy/blob/master/config/initializers/carrierwave.rb#L22 needs to be modified accordingly.

**Comment by KazW** [comment]
Unfortunately, that was the first thing I tried. Heroku is having some issues right now, so I can't manually restart my dynos to double check.

Any other thoughts on what it might be if it's not this?

**Comment by did** [comment]
@KazW well, I've recently simplified the configuration of Carrierwave when used a long withHeroku. Check our Locomotive Heroku repository here: https://github.com/locomotivecms/heroku-instant-deploy/blob/master/config/initializers/carrierwave.rb.
