### ISSUE TITLE
Localization and page meta_description

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/steam#45]
Hi,

I have an issue with the localization of the page meta_description

My site.yml has:

    locales: [en, fr, ru, zh-CN]

My default.liquid (layout) has:

     <meta name="description" content="{{ page.meta_description | escape }}">

My index.liquid has, in the header (yaml section):

    meta_description: "I am an English meta description"

My index.fr.liquid, index.ru.liquid and index.zh-cn.liquid have, in their respective header (yaml sections), the corresponding meta_description:

index.fr.liquid:

     meta_description: "Je suis une méta description française"

index.ru.liquid:

     meta_description: "Я русский мета-описания"

index.zh-CN.liquid:

     meta_description: "我是中国人描述"

When I am inspect the DOM of my rendered index.html file, in whichever version, it is filed in with the Chinese meta description:

      <meta name="description" content="我是中国人描述">

IT DOES NOT WORK.

Now, if I do:

default.liquid (layout):

     <meta name="description" content="{{ page.meta_description | escape }}">

index.liquid:

    meta_description:
       en: "I am an English meta description"
       fr: "Je suis une méta description française"
       ru: "Я русский мета-описания"
       zh-CN: "我是中国人描述"

IT WORKS.

The page seo_title has the same behavior.

But it is counter-intuitive, since we do have to create localized copies of the index.liquid file, to have to keep all the translations of the meta-description in the header of index.liquid.

At least, this should be documented in the internationalization section of the documentation.  :-)

**Comment by CedricLor** [comment]
Thanks Did. I updated to the latest version. The new behavior of page.seo_title and page.meta_description is as expected (each one in its own page).

**Comment by CedricLor** [comment]
However @did page.seo_title and site.seo_title are no longer accessible in the Engine.

**Comment by did** [comment]
@CedricLor looks like the page.seo_title is not pushed to the Engine.

**Comment by did** [comment]
My bad. These properties are not deployed unless you specify the dangerous "-d" option. "-d" is nice especially when you deploy for the first time or that if you haven't edited yet the content of your pages.

**Comment by CedricLor** [comment]
Thanks @did 

OK. Got it. This is the same issue as the one I described in the email I sent you with my logs regarding the phantom editable_elements that gets pushed, appear and then vanish.

All this data inserted in the header of the page (seo_title, editable_elements) gets pushed if you use the devilish -d option, but even though at first sight, they are displayed in the back office, they are not really there and vanish quickly. They are just an illusion ;-) You have to enter them manually again to really save them into the Engine.

That what happens when you rely on the devil to do things, but well... It would be convenient to be able to preload things
