### ISSUE TITLE
belongs_to and has_many not working properly with a scoping category applied to the holder

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/steam#48]
I have two content types: news and sitemembers
sitemembers has_many news
news belongs_to sitemembers

See my sitemembers.yml and news.yml below (after the logs). The relationships were generated by the CLI relationship generator of Wagon.

The versions of steam I am using is commit f00506074dd3. The error appears on the Wagon. I could not test on the Engine, since my Engine has not been running properly for about a week now.

I am trying to display the sitemember name corresponding to a given news on the news content_type_template page as follows :

        {{ news.sitemember.full_name }}

In Wagon, nothing appears.

I am trying to display the news related to a sitemember on the about page as follows:

      {% with_scope group: 'Board Member' %}
      {% for member in contents.sitemembers %}
                            {% for item in member.news %}
                              {{ item.title }}
                            {% endfor %}
      {% endfor %}
      {% endwith_scope %}

In Wagon, I get the error copied below. If I delete this part:

                            {% for item in member.news %}
                              {{ item.title }}
                            {% endfor %}

I do not have any problem scoping my members and displaying the other properties of my sitemember drop.

Why does steam need to seek for the "group" field (which is property of member) when I am trying to access the other content type????

       Arrrghhhh, we could not render page

      undefined method `group' for #

      File: ?

      Code

      No code

      Back trace

      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/models/entity.rb:22:in `method_missing'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/entities/content_entry.rb:34:in `method_missing'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/condition.rb:50:in `entry_value'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/condition.rb:22:in `matches?'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:94:in `block (2 levels) in filtered'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:93:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:93:in `block in filtered'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:90:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:90:in `find_all'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:90:in `filtered'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/adapters/memory/query.rb:68:in `all'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/repositories/content_entry_repository.rb:47:in `all'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:59:in `collection'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:8:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/utils.rb:23:in `slice_collection_using_each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/utils.rb:8:in `slice_collection'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:88:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:115:in `block (2 levels) in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:102:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:102:in `each_with_index'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:102:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:101:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-solid-4.0.1/lib/solid/block.rb:8:in `block (2 levels) in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/with_scope.rb:36:in `block in display'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/with_scope.rb:34:in `display'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-solid-4.0.1/lib/solid/block.rb:7:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-solid-4.0.1/lib/solid/element.rb:20:in `with_context'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-solid-4.0.1/lib/solid/block.rb:6:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/editable/model.rb:9:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:71:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:64:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:71:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:64:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:215:in `block in render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:269:in `with_profiling'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:214:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/liquid/template.rb:17:in `render'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/renderer.rb:34:in `parse_and_render_liquid'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/path.rb:13:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc4/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/dynamic_assets.rb:20:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-f00506074dd3/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
      /Users/cedriclor/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'

sitemembers.yml
-----------
    name: Site members
    slug: sitemembers
    description: A list of the site members
    label_field_name: full_name
    order_by: manually

    # A list describing each field
    fields:
    - full_name: # The lowercase, underscored name of the field
        label: Full name # Human readable name of the field
        type: string
        required: true
        localized: false

    - bio: # The lowercase, underscored name of the field
        label: Bio # Human readable name of the field
        type: text
        required: false
        hint: Please insert the member's bio here (will be displayed on the about page)
        localized: false
        text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)

    - group: # The lowercase, underscored name of the field
        label: Category # Human readable name of the field
        type: select
        required: false
        hint: Please insert the group to which the member belongs
        localized: false    # if localized, use
        #   en: ['option1_en', 'option2_en']
        #   fr: ['option1_fr', 'option2_fr']
        select_options: ['Contributor', 'Board Member', 'Executive']

    - news:
        label: News
        hint: A description of the relationship for the editors
        type: has_many
        class_name: news
        inverse_of: sitemember
        ui_enabled: true

news.yml
-----------
      name: News
      slug: news
      label_field_name: title
      order_by: posted_at
      order_direction: desc
      display_settings:
        seo: false
        advanced: false

      # A list describing each field
      fields:
      - title: # The lowercase, underscored name of the field
          label: Title # Human readable name of the field
          type: string
          required: true
          localized: true

      - posted_at: # The lowercase, underscored name of the field
          label: Posted at # Human readable name of the field
          type: date_time
          required: true
          localized: true

      - tags: # The lowercase, underscored name of the field
          label: Tags # Human readable name of the field
          type: tags
          required: false
          localized: false

      - teaser: # The lowercase, underscored name of the field
          label: Teaser # Human readable name of the field
          type: text
          required: false
          hint: "A short lead-in to the news, displayed when listing posts"
          localized: true
          text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)

      - featured_image: # The lowercase, underscored name of the field
          label: Featured image # Human readable name of the field
          type: file
          required: false
          hint: An image displayed next to the teaser when listing posts
          localized: false

      - body: # The lowercase, underscored name of the field
          label: Body # Human readable name of the field
          type: text
          required: true
          hint: The full news text
          localized: true
          text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)

      - photos:
          label: Photos
          type: has_many
          required: false
          localized: false
          class_name: photos # Define the slug of the target content type (eg. comments)
          inverse_of: news  # Define the name of the field referring to news in the target content type
          ui_enabled: true # If you want to manage the entries of the relationship directly from the source entry

      - events:
          label: Events
          hint: A news post may relate to many events and vice versa
          type: has_many
          required: false
          localized: true
          class_name: events # Define the slug of the target content type (eg. comments)
          inverse_of: news  # Define the name of the field referring to news in the target content type
          ui_enabled: true # If you want to manage the entries of the relationship directly from the source entry

      - sitemember:
          label: Site member
          hint: A description of the relationship for the editors
          type: belongs_to
          class_name: sitemembers

**Comment by did** [comment]
long story short: ````with_scope```` doesn't like "child queries". 
Longer explanation: https://github.com/locomotivecms/engine/issues/806

**Comment by did** [comment]
quick work-around:

````
  {% with_scope group: 'Board Member' %}
  {% for member in contents.sitemembers %}
     {% with_scope %} <!-- reset with_scope --->
                        {% for item in member.news %}
                          {{ item.title }}
                        {% endfor %}
    {% endwith_scope %}
  {% endfor %}
  {% endwith_scope %}
````

**Comment by CedricLor** [comment]
Got it. Thanks. Will try it today. Thanks a lot.

**Comment by rvalyi** [comment]
@did not sure resetting the scope is intuitive. May be worth having an alias like {% reset_scope %} that would be equivalent but may be explicit better the people reading a template why this line is here. Not sure, just thinking loud...

**Comment by CedricLor** [comment]
Well. While the scoping/rescoping issue is resolved, I am still not getting any output, neither on the news content_type_template with 

    {{ news.sitemember.full_name }}

nor on the about page with

    {% with_scope group: 'Board Member' %}
    {% for member in contents.sitemembers %}
       {% with_scope %} 
                        {% for item in member.news %}
                          {{ item.title }}
                        {% endfor %}
      {% endwith_scope %}
    {% endfor %}
    {% endwith_scope %}

If I do a 

    {{ member.news.count }}

it returns a 0 whereas I should have more (in my case, 3 precisely).

Just like if the relationship was not enforced.
