### ISSUE TITLE
Problem with views counter with the Engine v3

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/steam#49]
I would like to add some views counter to posts `content_type`.
My `app/content_types/posts.yml` includes new field `views` of `Integer type`:

    - views: 
        label: Counter
        type: Integer
        required: false
        hint: "Views counter (please do not edit)"
        localized: false

I've cloned `update` tag source of [liquid_extensions gem](https://github.com/locomotivecms/liquid_extensions/blob/master/lib/locomotive/liquid_extensions/tags/update.rb) to my private gem (testings). The reason is getting an error after bundle: 

    locomotivecms_liquid_extensions (>= 0) ruby depends on
      locomotivecms-solid (~> 0.2.2.1) ruby

My view has code like that:

    {% update post, views:post.views+1 %}
      <p>Views counter has been updated with success</p>
    {% else %}
      <p>Arrggh, there was an error.</p>
    {% endif_update %}

If I try to preview page unfortunately I'll get error message *undefined method `_visible' for #*.  
This problem is resolved by changing line 

    model.attributes = attributes
into:

    model.attributes = model.attributes.merge( attributes)

Now the counter works with success on **the Wagon only**.  
The Engine returns message

    LiveEditing] undefined method `save' for #<Locomotive::Steam::ContentEntry:0x000000035d1b70>`.

So, it seems that we cannot use `model.save`.

QUESTIONS

1. How to save changed views data on the Engine?
1. How to make better way for incrementing views field (without incrementing in the view )?
1. How to define hidden `views` field to avoid users changing in the Back-Office?
1. How to protect incrementing `views` counter from spam (I could refresh specific page many times for incrementing `views` counter)
1. I've found [colibri-software/visit_counter_hb_plugin](https://github.com/colibri-software/visit_counter_hb_plugin) gem. Is it possible to create something similar for Engine v3?

**Comment by did** [comment]
@adam-pl glad that you're bringing this up!

1/ that's impossible in v3, I mean not in the views which makes the liquid_extensions gem irrelevant. My main idea is to allow developers to write safe JS scripts that could be executed thru an URL OR like a callback. Inside these JS scripts, you'd have access to the whole Locomotive API. 
2/ my question is: why do you need to get the views? Where do you want to display them? Why not using GoogleAnalytics or something similar?
3/ there is the **ui_enabled** option in the field attributes but it's only used now for the has_many relationships. We could also use it for other fields :-)
4/ that's why GoogleAnalytics, Gaug.es, https://www.gosquared.com exist. I don't think re-developping that job makes sense.
5/ Totally. Just create your own liquid tag and call the site repository to persist the new counter value.

**Comment by adam-pl** [comment]
Thank you for your answers.

1. OK, JS scripts sounds good. But it's a little bit of work I guess. For my current problem I would like to resolve it by another way.
2. Users reads some posts. There are two major reasons that I need to count page views:

  1) users like to check how much viewed page is popular (i.e. 3 views means not popular, 30 views - quite popular, 3000 - very popular)
  2) I neet to add a box called "Most Popular (posts)" - If I had a "views" counter field I could sort posts by using `with_scope` tag)
3. Very good idea :-)
4. Thank you for mentioned gosquared.com service. I did not know about it. Generally So, I'll check it. I need to show box "Most Popular" for all people (not only for admin).
5. Hmmm... can you give me a short example how can I call the site repository and increment "views" field? I'm still learning it.

**Comment by adam-pl** [comment]
Ad. 5. After some investigation I tried to increment "views" field with following code of my tag:
```
def display(*options, &block)
  drop, attributes = self.extract_drop_and_attributes(options)
  model = drop.instance_variable_get(:@_source)
  return yield(false) if model.nil?
  if wagon
    model.attributes = model.attributes.merge( attributes)
  else
    model.views += 1
    current_context.registers[:services].entry_submission.submit( model._slug, model.attributes)
  end
  persisted = model.valid?
  self.log(model, persisted)
  ...
end
```

Unfortunatelly it doesn't work.

The key line is:
```
current_context.registers[:services].entry_submission.submit( model._slug, model.attributes)
```
model.views won't change event I'add line `model.views = 3333`. `model.views` field will still have 0 value instead of 3333.

What am I doing wrong?

If I change this line into:
```
current_context.registers[:services].entry_submission.submit( model._slug, attributes)
```
It also doesn't work.

**Comment by adam-pl** [comment]
If I debug mentioned line I get following info:
```
MONGODB | localhost:27017 | engine_dev.find | STARTED | {"find"=>"locomotive_content_types", "filter"=>{"site_id"=>BSON::ObjectId('568d21d8d5d4cf136e000000'), "slug"=>"my-post", "public_submission_enabled"=>true}, "limit"=>-1}
MONGODB | localhost:27017 | engine_dev.find | SUCCEEDED | 0.000568965s
```

**Comment by mlamarque** [comment]
Hello,
@adam-pl, what is your configuration ? wagon 2.0 and engine 3 ?
i have the same problem that you. where did you put this update tag ? engine side ? wagon ?
THanks

**Comment by adam-pl** [comment]
I use newest version of wagon and engine.

The problem concerns the Engine v3.

If I use following condition:
```
if wagon
    model.attributes = model.attributes.merge( attributes)
  else
    model.views += 1
    current_context.registers[:services].entry_submission.submit( model._slug, model.attributes)
  end
```
it will work fine int the Wagon (here I additionally use `plus: 1` filter.

It won't work on the Eingine.

Do you want to see entire source of my tag?

**Comment by mlamarque** [comment]
Yes i do,
where do you write this code, because if i understand well (sorry i begin with wagon/locomotive etc..) in wagon app there are only the front code.

**Comment by adam-pl** [comment]
My view is:
  ```
  {% if_update post, views:post.views+1 %}
    <span class="page-views">{{ 'page_views' }}</span>
  {% endif_update %}
  ```
My tag is:
  ```
module Locomotive
  module KoalaLiquidExtensions
    module Tags

      class IfUpdate < Solid::ConditionalBlock

        tag_name :if_update

        context_attribute :wagon

        def display(*options, &block)
          drop, attributes = self.extract_drop_and_attributes(options)
          model = drop.instance_variable_get(:@_source)

          return yield(false) if model.nil?

          if wagon
            model.attributes = model.attributes.merge( attributes)
            # save the model in the engine or just process the validation if in Wagon
          else
            model.views = model.views + 1
          end

          persisted = model.valid?
    
          # log the last statement
          self.log(model, persisted)

          yield(persisted)
        end

        protected

        def extract_drop_and_attributes(options)
          raise Liquid::Error.new("[update] wrong number of parameters (2 are required instead of #{options.size})") if options.size != 2

          [options.first, options.last].tap do |drop, attributes|
            if attributes.is_a?(Hash)
              attributes.each do |k, v|
                _source = v.instance_variable_get(:@_source)

                attributes[k] = _source if _source
              end

              attributes.delete_if { |k, _| %w(site site_id content_type content_type_id).include?(k.to_s) }
            else
              raise Liquid::Error.new('[update] wrong attributes')
            end
          end
        end

        def log(model, persisted)
          message = persisted ? ["Model updated !"] : ["Model not updated :-("]
          message << "  attributes: #{model.to_s}"

          current_context.registers[:logger].info message.join("\n") + "\n\n"
        end

      end

    end
  end
end
  ```

Note that for the Engine incrementing is done only by one (plus: 1 is ignored) - jest tests in progress.

**Comment by did** [comment]
@adam-pl @mlamarque I coded "quickly" a very simple solution for you guys. https://github.com/did/locomotive_view_counter. 
It requires one of the very last commits of Steam.
