### ISSUE TITLE
link_to problem

### ISSUE THREAD

**Issue by sergiipopov** [locomotivecms/steam#51]
Code:
    ```<div class="portfolio-item">
      {% link_to hotels %} Hotels {% endlink_to %}
    </div>```

Renders to:
   ```<div class="portfolio-item">
    </div>```

Link_to dosn't render link

**Comment by gcolson** [comment]
Same issue here, `link_to` tag does not seem to work with page handles as it should be according to [the doc](https://doc.locomotivecms.com/docs/tags#link_to)

**Comment by did** [comment]
thanks @gcolson. This should work (https://github.com/locomotivecms/steam/blob/master/spec/unit/liquid/tags/link_to_spec.rb#L52). 
Are you sure your `hotels` variable is not nil?

**Comment by did** [comment]
sorry, I didn't see the rest of the conversation here: https://doc.locomotivecms.com/discuss/60461812049c93001eefc531.
