### ISSUE TITLE
The Wagon hangs with locomotivecms_steam 1.0.0.rc10 / 1.0.0

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/steam#54]
I have a project that works fine with the Wagon & steam 1.0.0.rc9.
If I update steam to `1.0.0.rc10` version the Wagon will hang - Internet Browser will never load page on http://localhost:3333/.

##### 1. The Wagon with working gems:
```
gem 'locomotivecms_wagon', '2.0.0.rc6'
gem 'locomotivecms_steam', '1.0.0.rc9'
gem 'locomotivecms_coal', '1.0.0.rc4'
```

##### 2. The Wagon does not work with gems:
```
gem 'locomotivecms_wagon', '2.0.0.rc6'
gem 'locomotivecms_steam', '1.0.0.rc10'
gem 'locomotivecms_coal', '1.0.0.rc4'
```

##### 3. The Wagon does not work with gems:
```
gem 'locomotivecms_wagon', '2.0.0'
gem 'locomotivecms_steam', '1.0.0'
gem 'locomotivecms_coal', '1.0.0'
```

If I turn on `Thin web server` debug mode nothing is logged.

What reason is the Wagon hangs with steam '1.0.0.rc10'?
How to run the Wagon in debug mode?

**Comment by adam-pl** [comment]
The problem is connected with stylesheets.
If I remove `public/stylesheets` of site project, the Wagon works fine with steam '1.0.0.rc10'.

**Comment by adam-pl** [comment]
If I change following line of file `/home/adam/.rvm/gems/ruby-2.1.1/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/dynamic_assets.rb`
```
@assets = self.class.sprocket_environment(options[:root], options)
```
into
```
@assets = Locomotive::Steam::SprocketsEnvironment.new(options[:root], options)
```
the Wagon will work with stylesheets and steam '1.0.0'.

**Comment by adam-pl** [comment]
If I change following line in `/home/adam/.rvm/gems/ruby-2.1.1/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/initializers/sprockets.rb` file:
```
AutoprefixerRails.install(self, params)
```
the Wagon will work with stysheets & steam 1.0.0.

**Comment by did** [comment]
@adam-pl AutoprefixerRails is known to hang. It happens if the css files are big, well, that's what I noticed. 

A quick word-around is to use NodeJS for the JS engine. 

````
EXECJS_RUNTIME=Node bundle exec wagon serve
````

Perhaps, I should disable the autoprefixer feature (opt-in).

**Comment by did** [comment]
@adam-pl quick question: what's in your Wagon Gemfile?

**Comment by adam-pl** [comment]
**1.** I've been testing this problem on new project then copying source `public/stylesheets` folder's content file by file every time running 'bundle exec wagon serve -v'.
If I copy 7 small files (totally 7 kB) the Wagon will hang.

My Gemfile of testing project is standard (generated by command `bundle exec wagon init w`):
```
source 'https://rubygems.org'

gem 'locomotivecms_wagon', '~> 2.0.0'
#gem 'execjs'

# gem 'guard-livereload', '~> 2.5.1'

group :development do
  # Mac OS X
  gem 'rb-fsevent', '~> 0.9.1', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')

  # Unix
  gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')

  gem 'rb-inotify', '~> 0.9', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

  # Windows
  gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
end

group :misc do
  # Add your extra gems here
  # gem 'susy', require: 'susy'
  # gem 'bourbon', require: 'bourbon'
end
```

Should I add `gem 'execjs', '~> 2.6'`?

**2.** Running the Wagon with `EXECJS_RUNTIME=Node bundle exec wagon serve` helps totally.

@did, Thank you for your advice. 
Adding `export EXECJS_RUNTIME='Node'` to my environment resolve my problem.

The worst thing was I did not get any message to guess what the problem was. As I mentioned the problem appeared after `bundle update`.

**3.** Disabling the autoprefixer option
It would be great to add debug mode in the Wagon instead of uncommenting following line
```
# Thin::Logging.debug = true
```
in the `/home/adam/.rvm/gems/ruby-2.1.1/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon/commands/serve_command.rb` file.

If I get suitable warning about autoprefixer value in debug mode that will be enough.
If EXECJS_RUNTIME environment is empty the Wagon should warn about (even debug mode is turned off) I think.

**Comment by jepetko** [comment]
I was struggling with the same issue. In fact, setting env variable EXECJS_RUNTIME=Node solved my problem.

**Comment by StephanieSunshine** [comment]
I was having a hard time trying to figure this one out.  It seems with strace wagon would run just fine, but without it, lockups almost every time.  This solved all my problems perfectly.

**Comment by did** [comment]
if you want now to use autoprefixer, just add the ````config/autoprefixer.yml```` file in your Wagon site. It also works with an empty file.
