### ISSUE TITLE
Enhance the documentation for localization

### ISSUE THREAD

**Issue by jepetko** [locomotivecms/steam#57]
I spent much time debugging steam because the request http://localhost:3333/en ("en" is the secondary language; locales = [de, en]) returned "Missing 404 page". This is because the page could not be found:

render.rb:
```ruby
      def _call
        if page
          render_page
        else
          render_missing_404
        end
      end
```

Since the 404 page is not localized the message "Missing 404 page" appears. 

The reason is that you need to duplicate your pages for using localization (index.liquid gets index.de.liquid and index.en.liquid). The documentation https://locomotive-v3.readme.io/docs/localization doesn't mention this in any way. 
Despite this annoying issue... good work! I like the architecture of the steam gem.

**Comment by did** [comment]
hi @jepetko, we definitively need to change that "annoying" behaviour. I see 2 options:
- update the documentation as you mentioned it
- find the page in the default locale => not sure if we want to have that in any context.
Any thoughts?

**Comment by jepetko** [comment]
I think there is no need to have two files. I know that in some cases there will be a file necessary for the secondary language (for example to define editable element values). In case that there is no file at all (index.en.liquid) steam should process index.liquid. If this is not possible (because of some technical limitations) an appropriate error should be raised, for instance "there is no template to render page/en. Please add page.en.liquid accordingly..." or something like that. If there is no page.liquid the fallback is (of course) 404.liquid.

**Comment by did** [comment]
@jepetko what about this use case in production. Let's say you've got your "Contact" page and it isn't translated in German ("Kontakt"). What should people see when they browse /kontakt? The German 404 page or the page in English?

**Comment by jepetko** [comment]
I would actually expect to see an "unlocalized" page but now I'm not sure if it's something the visitor wants to see. Maybe the current solution is the best one but I would provide more debugging messages to the caller.

```
Originally requested page: index.de.liquid
Originally requested page state: 404 (Not Found)
Fallback page: 404.de.liquid
Fallback page state: 404 (Not Found)
```

This would give the maintainer an idea about what is wrong.

**Comment by did** [comment]
@jepetko. Here are the output when a page is missing or the 404 error page

````bash
Localized
Started GET "/fr/foo" at 2016-02-16 10:46:40 +0100
  Params: {}
  Timezone: UTC
  Detecting locale FR
  [Tip] add a new page in your Wagon site at this location: /Users/didier/Sites/localized/app/views/pages/foo.fr.liquid
  Page not found, rendering the 404 page.
  Completed 404 Not Found in 40.7ms
````

````bash
Localized
Started GET "/fr/foo" at 2016-02-16 10:11:16 +0100
  Params: {}
  Timezone: UTC
  Detecting locale FR
  [Warning] Your 404 page is missing in the fr locale. Please create it.
  Completed 404 Not Found in 44.2ms
````
