### ISSUE TITLE
Page won't render if nav tag used with snippet option

### ISSUE THREAD

**Issue by tap87** [locomotivecms/steam#59]
I am trying to use the nav tag with snippet option:
 {% nav site, no_wrapper: true, active_class: active, snippet: primary-nav %}
But the page won't render. Error copied below:

`Arrrghhhh, we could not render page

undefined method `split' for #

File: ?

Code

No code

Back trace

/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:237:in `tokenize'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:110:in `parse'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/nav.rb:260:in `parse_snippet_template'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/nav.rb:233:in `set_template_if_asked'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/nav.rb:34:in `render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:215:in `block in render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:269:in `with_profiling'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:214:in `render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/template.rb:17:in `render'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:34:in `parse_and_render_liquid'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/path.rb:13:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/dynamic_assets.rb:22:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `call'
/Users/tap87/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'`

**Comment by did** [comment]
hi @tap87, are you sure ````primary-nav```` is the name of your snippet? Do you have a ````primary-nav.liquid```` file under the app/views/snippets folder?

**Comment by tap87** [comment]
hi @did . Yes, I have primary-nav.liquid file in the snippets folder. Here is the [repo](https://github.com/cul-it/mann-wagon/tree/nav-snippet/app/views/snippets)

**Comment by did** [comment]
@tap87, bug reproduced locally.
