### ISSUE TITLE
Customize Renderer

### ISSUE THREAD

**Issue by cpvinh** [locomotivecms/steam#60]
Hi @did 

I copied renderer.rb to myapp/lib/locomotive/steam/middlewares/renderer.rb and adjust that file but it's not worked actually. How can I custom the renderer? 

**This is my case**: I have parent page with name 'pages' and the child pages with name 'test'. Currently, when I want to see that page, I will browse the path /pages/test. So can I use the path /test? If possible, please help me the solution.

Thank you.

**Comment by did** [comment]
hi @cpvinh, sorry for the delay. Here are some information for what you were trying to achieve: https://locomotive-v3.readme.io/docs/custom-rendering.
And regarding your case, it's currently not possible.
