### ISSUE TITLE
Unlocalized content types on multilingual sites leads to duplicate content

### ISSUE THREAD

**Issue by robinlambert** [locomotivecms/steam#63]
Let's say I have a multilingual site in English (default language) and French.
I create a content type blog_posts and all of its fields are set to `localized: false`.
When I create a blog post, it is accessible with `my-blog-post-slug` but also with `fr/my-blog-post-slug`. So I have duplicate content on my website.
`fr/my-blog-post-slug` should be a 404 or a redirection to `my-blog-post-slug`

**Comment by did** [comment]
thanks @robinlambert
