### ISSUE TITLE
Allow editing FOR LOOP output order through backoffice

### ISSUE THREAD

**Issue by maniksingh92** [locomotivecms/steam#64]
The backoffice allows you to drag and move the position of entries of a data model up and down, but the view reflects the original positioning of the entries.

Is there is a way to automatically update the order of the output of a for loop tag in the view by dragging and moving the entries of a content model?

To achieve what i want, I've to currently do this:
1. drag and move the position of the entries of a data model according to the desired order
2. sync content resource from engine to wagon (this gets the desired order in the data yml of the model)
3. delete the specific content resource from the engine
4 .push content resource from wagon to engine (now engine displays the order of the entries correctly in the view)

Thanks

**Comment by did** [comment]
hey @maniksingh92, actually I couldn't reproduce this bug. Do you still have the bug?
