### ISSUE TITLE
Conditional extends doesn't work

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/steam#66]
In short:

**1. My view has following condition**:

```
{% if true %}
  {% extends 'templates/main' %}
{% endif %}
```

I get following info in my browser:

> 
> Arrrghhhh, we could not render page
> 
> Liquid syntax error: 'if' tag was never closed
> 
> File: ?
> 
> Code
> 
> No code
> 
> Back trace
> 
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:68:in `block in parse_body'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:55:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/if.rb:24:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
> /home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'

**2. If I change it into**:

```
{% if true %}
{% endif %}
{% extends 'templates/main' %}
```

then my page will load properly.

**3. Is it possible to use conditional extends?**

**Comment by adam-pl** [comment]
I've tried to write custom tag `my_extends` that could accept conditional template like that:
```
{% assign template_index = 1 %}
{% my_extends, template: 'templates/first', template: 'templates/second', index: template_index %}
```

The example  should select template with index 1 ->  `templates/second`.

Unfortunately I can't find a way for evaluating `template_index` variable's value at parse level.
The steam has following method:
```
module Locomotive::Steam
  module Middlewares

    class Renderer < ThreadSafe
      ...
      def parse_and_render_liquid
        document = services.liquid_parser.parse(page)
        document.render(liquid_context)
      end
      ...
    end
  end
end
```

At first step (while executing `document = services.liquid_parser.parse(page)`) there is called `parse_parent_template` method of the `MyExtends` class that requires `@template_name` param. 
At this step we do not have a context and we cannot give `@template_name` suitable to `template_index` variable index.

If I had a context I could retrieve `template_index` value like that:

1. Calling `prepare_index` in the initialize
  ```
  def initialize(tag_name, markup, options)
    super
    @template_names = []
    @template_index = 0
    markup.scan(::Liquid::TagAttributes) do |key, value|
    case key.to_sym
      when :template              
        if value =~ Syntax
          @template_names << $1.gsub(/["']/o, '').strip
        else
          raise(::Liquid::SyntaxError.new(options[:locale].t("errors.syntax.extends".freeze)))
        end
      when :index
        prepare_index( value)
      else
        raise(::Liquid::SyntaxError.new("unsupported my_extends param '#{key}'"))
      end
    end

    def prepare_index(token)
      if token.match(::Liquid::QuotedString)
        @template_index = token.gsub(/['"]/, '').to_i
      else
        @variable_index = token
      end
    end
  ```
Note: @variable_index has our variable name called `template_index`.
2. Retrieving variable's value:

    ```
    if instance_variable_defined?(:@variable_index)
      @template_index = context[@variable_index]
      @template_name = @template_names[[@template_index, @template_names.size - 1].min]
    end
    ```

Do you know how to evaluate variable's data at parsing step?

**Comment by adam-pl** [comment]
Finally I've dropped my idea with conditional templates.
Now I use only one template.

**Comment by did** [comment]
@adam-pl I won't recommend conditional extends. Besides, it would break the inline editing part. 
Btw, you can't evaluate the value of a variable while parsing a liquid template.

**Comment by adam-pl** [comment]
Ok, thank you for the info... Now I use only one template.
