### ISSUE TITLE
Difference in behaviour when checking strings on local vs. deployed

### ISSUE THREAD

**Issue by SuperSchek** [locomotivecms/steam#70]
When checking whether or not a string is present in a content entry I've noticed some difference in behaviour between my local environment and my staging environment.

Locally `{% if project.youtube_video %}` works fine for me. However, when deployed it always evaluates to true so I have to use '{% if project.youtube_video != "" %}'. The latter case always evaluates to true on local but seems to work fine in my staging environment.

**Comment by did** [comment]
hi @SuperSchek. You shouldn't rely on nil values for your metafields. The issue is that, in your back-office (Engine), if you save your metafields, we'll store empty string values instead of nil ones. 

So, use ```{% if project.youtube_video != "" %}``` instead which looks fine to me.
