### ISSUE TITLE
Sitemap.xml is returning elements that are not translated

### ISSUE THREAD

**Issue by gillesbertaux** [locomotivecms/steam#71]
Sitemap.xml should return only elements that have localized at true. If the Blog posts content type are not translated they should not appear in the sitemap. 

Condition here is incomplete: https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/services/url_builder_service.rb#L19

It should check if the page has a content entry (Templatized) and if its related content type is translated or not.

**Comment by did** [comment]
@gillesbertaux. so the rule is the following: we don't display content entries of a non localized content type in the locales other than the default one IF the template of that page is also "non localized". In other words, the template of the templatized page has to be blank in all the locales other than the default one.
