### ISSUE TITLE
Merge upstream changes to liquid fork?

### ISSUE THREAD

**Issue by cappadona** [locomotivecms/steam#76]
Hey @did. Just [commented in Gitter](https://gitter.im/locomotivecms/v3?at=57b484e35a4ad6105682beba) as well. Would be great if we can take advantage of the some of the Liquid improvements introduced upstream. I'm especially interested in using the new [whitespace controls](https://github.com/Shopify/liquid-c/pull/30).

Let me know if I can help.

**Comment by did** [comment]
fixed by #160. better late than never :-)
