### ISSUE TITLE
Documentation for registering custom filters

### ISSUE THREAD

**Issue by jordanthomas** [locomotivecms/steam#78]
I've been working on developing a gem with custom Liquid filters for a project by piecing together some code. It works locally with Wagon but fails once deployed.

It would be nice to have some documentation around registering custom filters. It would be extra nice if there were a boilerplate project you could clone and modify.

I'm sure I'm missing something simple and these things could help me debug my project.

**Comment by did** [comment]
sorry, super old issue but we finally wrote a piece of documentation about it here: https://locomotive-v3.readme.io/docs/custom-rendering.

**Comment by aizad02** [comment]
Hi @did sorry for reopening, But i believe tried to follow the documentation and seems it's not working. The products does not show any result in liquid.
