### ISSUE TITLE
SEO tag - add rel: alternate links for locales?

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/steam#82]
How about adding alternate link tags to the SEO tag to potentially boost rankings of international sites?

I.e. for each available locale except for the current one,
```
<link rel="alternate" hreflang="<locale>" href="<translated page path>" />
```
for the current locale use `hreflang="x"` and additionally for the default language
```
<link rel="alternate" hreflang="x-default" href="<translated page to default locale>" />
```
Would love to see Loco featuring more SEO out of the box in the future.

Alternatively, we could implement this directly in the sitemap with the advantage that the locale meta info is also available on sites where the seo tag is not used, by default.

**Comment by did** [comment]
hi @banditrider, agreed! We could also add the twitter:card and facebook open graph meta tags in addition of the default title, meta keywords and meta description? What do you think?
