### ISSUE TITLE
customize/overwrite locale translations of locale switcher 

### ISSUE THREAD

**Issue by f3dd3rn** [locomotivecms/steam#84]
As discussed with @did in the locomotive gitter chat, here is my issue description.

I want to overwrite/customize locale translations of locale switcher.
Goal is, that the translation of locale remains the same in that locale no matter what the current locale.
Example: Français remains Français even though the page is currently in English and English remains English.

In order to accomplish that, I tried to overwrite `config/locales/en.yml` and `config/locales/fr.yml`:
```
en:
  locomotive:
    locales:
      fr: Français

fr:
  locomotive:
    locales:
      en: English
```

Quote from chat with @did:
> we rely on I18n.t("locomotive.locales.#{locale}”) by default
> which is not correct
> because there is no way a Locomotive developer can modify it on the hosting platform for instance
> https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/tags/locale_switcher.rb#L59
> instead we should verify if a such translation exists in the translations.yml file and if not fallback to I18n.

**Comment by nik736** [comment]
I've added a new language in the locomotive initializer and now I am obviously receiving:
translation missing: en.locomotive.locales.hu

I tried adding that to the translations.yml file but it's not taking it from there. What are my options to get it to work?

Thanks! :)
