### ISSUE TITLE
SSL on editable_file

### ISSUE THREAD

**Issue by merqlove** [locomotivecms/steam#87]
All file tag asserts has http protocol on non ssl domain, which is being loaded under HTTPS engine domain.

**Comment by did** [comment]
hi @merqlove! Not sure to understand. What do you mean by "file tag asserts"? thanks!

**Comment by merqlove** [comment]
Hi @did, As i remember i added some decorators locally for this bug.
Here is a problems if you have http-only domains under base https on backend. 
Or if you trying to load https domain via http.
Lots of them  being produced when Dragonfly provide some content.

**Comment by merqlove** [comment]
Currently I can not find time for this PR, too many fixes have been made(including iframe params), but most of them as decorators.

**Comment by did** [comment]
thanks @merqlove for the explanations. Could it also be a wrong Dragonfly configuration?

**Comment by merqlove** [comment]
Sure,
I have added https url_host for Engine & Steam Dragonfly both + forced everywhere https for dragonfly where sometimes is none (such areas as metafields).

**Comment by did** [comment]
makes definitively sense. When you'll have time, post your modifications here, I will update Engine/Steam accordingly. thanks again!

**Comment by merqlove** [comment]
@did , ok, i will do it asap.

**Comment by did** [comment]
editable_elements (including editable_files) are now considered as deprecated because of the new sections (https://doc.locomotivecms.com/v4.0/docs/section-introduction)
