### ISSUE TITLE
Sitemap is unaccessible if content entry mounted directly after root

### ISSUE THREAD

**Issue by MrRezaque** [locomotivecms/steam#92]
Hi,

When you mount content entry template right after root (yoursite.xyz/entry_slug), sitemap becomes inaccessible, it seems to search for an entry and then fails with 404. Thing is that steam somehow considers that page is existing even when no slug matches sitemap.xml (page.nil? || page.not_found? both return false https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/middlewares/sitemap.rb#L9)

steam 1.2.1

Since It's not critical for my current project, I considered to move this entry to another path, but I guess it should be fixed. It's very confusing when sitemap supposed to work and had worked before just stops from showing. 

Thanks, Yar.

**Comment by did** [comment]
hi @MrRezaque, the sitemap route should have the priority over the content entry template. let me check.

**Comment by did** [comment]
Can't reproduce it, it should have fixed some time ago.
